apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: swserver-steam-login-pvc
  namespace: game-servers
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: swserver-steamcmd-pvc
  namespace: game-servers
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: swserver-wine-pvc
  namespace: game-servers
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: swserver-gamedata-pvc
  namespace: game-servers
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
