apiVersion: v1
kind: Service
metadata:
  name: swserver-nodeport
  namespace: game-servers
spec:
  type: NodePort
  ports:
    - name: tcp-25564
      protocol: TCP
      port: 25564
      targetPort: 25564
      nodePort: 32564
    - name: udp-25564
      protocol: UDP
      port: 25564
      targetPort: 25564
      nodePort: 32565
    - name: tcp-25565
      protocol: TCP
      port: 25565
      targetPort: 25565
      nodePort: 32566
    - name: udp-25565
      protocol: UDP
      port: 25565
      targetPort: 25565
      nodePort: 32567
    - name: tcp-25566
      protocol: TCP
      port: 25566
      targetPort: 25566
      nodePort: 32568
    - name: udp-25566
      protocol: UDP
      port: 25566
      targetPort: 25566
      nodePort: 32569
    - name: panel
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32580
  selector:
    app: swserver
